# Generated by Django 5.2.12 on 2026-04-17 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_user_passage_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=51)),
                ('codigo_iso', models.CharField(max_length=2)),
                ('custo_de_vida', models.CharField(max_length=20)),
                ('idioma', models.CharField(max_length=50)),
                ('cultura', models.TextField()),
                ('descricao', models.TextField()),
                ('imagem_url', models.CharField(max_length=250)),
                ('intercambistas', models.IntegerField()),
                ('universidades', models.IntegerField()),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'pais',
                'verbose_name_plural': 'Países',
            },
        ),
    ]
