<<<<<<< HEAD
# Generated by Django 6.0.5 on 2026-05-29 11:28
=======
# Generated by Django 5.2.12 on 2026-05-29 00:19
>>>>>>> 289fa94c1f4936b52638944d9ad93eb60400886c

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_pais'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='perfil/'),
        ),
    ]
