# Generated by Django 5.2.12 on 2026-06-03 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_agencia_programa_avaliacao_estado_plano'),
        ('core', '0007_user_foto'),
    ]

    operations = [
    ]
