# Generated by Django 5.2.12 on 2026-06-26 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_agencia_programa_avaliacao_estado_plano'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Foto de perfil do usuário.', null=True, upload_to='avatars/', verbose_name='foto de perfil'),
        ),
    ]
