# Generated by Django 5.2.12 on 2026-07-01 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano',
            name='inclui',
            field=models.TextField(blank=True, default=''),
        ),
    ]
