# Generated by Django 5.2.12 on 2026-08-22 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_merge_20260603_1510'),
        ('core', '0009_plano_inclui'),
    ]

    operations = [
    ]
