# Generated by Django 5.2.12 on 2026-07-09 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_plano_inclui'),
    ]

    operations = [
        migrations.AddField(
            model_name='pais',
            name='programas_disponiveis',
            field=models.IntegerField(default=0),
        ),
    ]
