# Generated by Django 5.2.12 on 2026-08-23 05:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_merge_0008_merge_20260603_1510_0009_plano_inclui'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencia',
            name='id_estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agencias', to='core.estado'),
        ),
        migrations.AddField(
            model_name='agencia',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agencia', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pais',
            name='regiao',
            field=models.CharField(blank=True, choices=[('asia', 'Ásia'), ('europa', 'Europa'), ('america_norte', 'América do Norte'), ('america_sul', 'América do Sul'), ('oceania', 'Oceania'), ('africa', 'África')], max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='tipo',
            field=models.CharField(choices=[('estudante', 'Estudante'), ('agencia', 'Agência')], default='estudante', help_text='Estudante ou agência de intercâmbio.', max_length=20, verbose_name='tipo de conta'),
        ),
    ]
