# Generated by Django 5.2.12 on 2026-08-23 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_agencia_id_estado_agencia_usuario_pais_regiao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pais',
            name='nome_ingles',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('emprego', 'Emprego'), ('universidade', 'Universidade'), ('idioma', 'Idioma'), ('cultura', 'Cultura')], max_length=20)),
                ('valor', models.SlugField(max_length=30)),
                ('label', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['categoria', 'valor'],
                'unique_together': {('categoria', 'valor')},
            },
        ),
        migrations.AddField(
            model_name='agencia',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='agencias', to='core.tag'),
        ),
        migrations.AddField(
            model_name='pais',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='paises', to='core.tag'),
        ),
    ]
