# Generated by Django 5.2.12 on 2026-08-23 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_pais_nome_ingles_tag_agencia_tags_pais_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.SlugField(blank=True, default='', help_text='Usado na URL do perfil público (/usuarios/<username>).', max_length=40, verbose_name='nome de usuário'),
        ),
    ]
