# Generated by Django 5.2.12 on 2026-08-23 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_backfill_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.SlugField(blank=True, help_text='Usado na URL do perfil público (/usuarios/<username>).', max_length=40, unique=True, verbose_name='nome de usuário'),
        ),
    ]
