# Generated by Django 5.2.12 on 2026-08-23 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencia',
            name='como_funciona',
            field=models.TextField(blank=True, default='', help_text='Explicação, em texto livre, de como é o processo de inscrição/atendimento dessa agência.', verbose_name='Como funciona'),
        ),
    ]
