# Generated by Django 5.2.12 on 2026-08-25 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_favorito'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencia',
            name='layout',
            field=models.JSONField(blank=True, default=list, help_text='Lista ordenada de seções e variantes escolhidas pela agência no editor de página (conta business). Vazio = layout padrão.', verbose_name='Layout da página'),
        ),
        migrations.AddField(
            model_name='agencia',
            name='paises_atendidos',
            field=models.ManyToManyField(blank=True, help_text='Todos os países onde a agência tem unidade/atuação — inclui o país da sede.', related_name='agencias_atendidas', to='core.pais', verbose_name='Países atendidos'),
        ),
        migrations.AlterField(
            model_name='agencia',
            name='id_estado',
            field=models.ForeignKey(blank=True, help_text='Cidade/estado da sede da agência — usado no endereço e como localização principal.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agencias', to='core.estado', verbose_name='Sede'),
        ),
    ]
