# Generated by Django 5.2.12 on 2026-08-25 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_agencia_layout_agencia_paises_atendidos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencia',
            name='imagem_capa',
            field=models.ImageField(blank=True, help_text='Banner exibido no topo da página quando a variante "banner cheio" do hero está selecionada.', null=True, upload_to='agencias/capas/', verbose_name='Imagem de capa'),
        ),
    ]
