# Generated by Django 5.2.12 on 2026-08-25 00:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_agencia_imagem_capa'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoAgencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('site', models.CharField(blank=True, max_length=255)),
                ('cidade', models.CharField(max_length=100)),
                ('ano_fundacao', models.PositiveIntegerField(blank=True, null=True)),
                ('nome_responsavel', models.CharField(max_length=100)),
                ('cargo_responsavel', models.CharField(blank=True, max_length=100)),
                ('email_responsavel', models.EmailField(max_length=254)),
                ('documento', models.FileField(upload_to='solicitacoes_agencia/documentos/')),
                ('descricao', models.TextField(blank=True, help_text='Por que a agência deveria estar na GlobalBridge.')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('recusado', 'Recusado')], default='pendente', max_length=10)),
                ('motivo_recusa', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('revisado_em', models.DateTimeField(blank=True, null=True)),
                ('agencia_criada', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacao_origem', to='core.agencia')),
                ('pais_sede', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_sede', to='core.pais')),
                ('paises_atendidos', models.ManyToManyField(blank=True, related_name='solicitacoes_atendidas', to='core.pais')),
                ('usuario_criado', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacao_agencia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitação de agência',
                'verbose_name_plural': 'Solicitações de agência',
                'ordering': ['-criado_em'],
            },
        ),
    ]
