# Generated by Django 5.2.12 on 2026-08-25 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_solicitacaoagencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=6)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usado', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigos_login', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Código de login',
                'verbose_name_plural': 'Códigos de login',
                'ordering': ['-criado_em'],
            },
        ),
    ]
