# Generated by Django 5.2.12 on 2026-08-25 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_codigologin'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoPaisAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('recusado', 'Recusado')], default='pendente', max_length=10)),
                ('motivo_recusa', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('revisado_em', models.DateTimeField(blank=True, null=True)),
                ('agencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_pais', to='core.agencia')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_adicionais', to='core.pais')),
            ],
            options={
                'verbose_name': 'Solicitação de país adicional',
                'verbose_name_plural': 'Solicitações de país adicional',
                'ordering': ['-criado_em'],
            },
        ),
    ]
