# Generated by Django 5.2.12 on 2026-08-25 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_solicitacaopaisadicional'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencia',
            name='conteudo_blocos',
            field=models.JSONField(blank=True, default=dict, verbose_name='Conteúdo das seções'),
        ),
        migrations.AddField(
            model_name='agencia',
            name='imagem_capa_foco_x',
            field=models.FloatField(default=50),
        ),
        migrations.AddField(
            model_name='agencia',
            name='imagem_capa_foco_y',
            field=models.FloatField(default=50),
        ),
        migrations.CreateModel(
            name='ImagemGaleria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='agencias/galeria/')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('agencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeria', to='core.agencia')),
            ],
            options={
                'verbose_name': 'Imagem da galeria',
                'verbose_name_plural': 'Imagens da galeria',
                'ordering': ['ordem', 'id'],
            },
        ),
    ]
