# Generated by Django 5.2.12 on 2026-08-27 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_agencia_conteudo_blocos_agencia_imagem_capa_foco_x_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoVerificacaoEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('codigo', models.CharField(max_length=6)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usado', models.BooleanField(default=False)),
                ('verificado', models.BooleanField(default=False)),
                ('verificado_em', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Código de verificação de e-mail',
                'verbose_name_plural': 'Códigos de verificação de e-mail',
                'ordering': ['-criado_em'],
            },
        ),
    ]
