# Generated by Django 5.2.12 on 2026-08-28 00:56

import core.models.solicitacao_agencia
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_codigoverificacaoemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacaoagencia',
            name='documento',
            field=models.FileField(storage=core.models.solicitacao_agencia._storage_documento, upload_to='solicitacoes_agencia/documentos/'),
        ),
    ]
